<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_shopByCategory</name>
   <tag></tag>
   <elementGuidId>3442a1f1-5111-4dc0-9bc8-d89a1f8e6466</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/main[1]/section[1]/main[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'flex flex-col justify-center gap-5 px-3 items-center' and (text() = 'Shop by CategoryRacketRackets are the most important part of the game. Choose the best racket for you....[truncated lines=146]' or . = 'Shop by CategoryRacketRackets are the most important part of the game. Choose the best racket for you....[truncated lines=146]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>main &gt; div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col justify-center gap-5 px-3 items-center</value>
      <webElementGuid>5f9ddd24-420c-4667-88ec-8ccc6abd7844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop by Category
Racket

Rackets are the most important part of the game. Choose the best racket for you.

...[truncated lines=146]</value>
      <webElementGuid>5f9ddd24-420c-4667-88ec-8ccc6abd7844</webElementGuid>
   </webElementProperties>
</WebElementEntity>
