<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>main_productDetails</name>
   <tag></tag>
   <elementGuidId>94793536-ee9f-49e5-a8e7-ad2b4e94ea48</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/main[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'flex justify-center py-10 h-full flex-grow overflow-auto' and (text() = 'Victor Auraspeed 100X Ultra New 2025In stock: 22Brand: VICTORStatus:UNAVAILABLE...[truncated lines=27]' or . = 'Victor Auraspeed 100X Ultra New 2025In stock: 22Brand: VICTORStatus:UNAVAILABLE...[truncated lines=27]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>main</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-center py-10 h-full flex-grow overflow-auto</value>
      <webElementGuid>5f9ddd24-420c-4667-88ec-8ccc6abd7844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Victor Auraspeed 100X Ultra New 2025
In stock: 22
Brand: VICTOR
Status: 
UNAVAILABLE
...[truncated lines=27]</value>
      <webElementGuid>5f9ddd24-420c-4667-88ec-8ccc6abd7844</webElementGuid>
   </webElementProperties>
</WebElementEntity>
